name: CI

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
          rustup component add clippy rustfmt
      - name: Format
        run: cargo fmt --check
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Lint
        run: cargo clippy
